import { CommandRegistry } from '@clashmate/discord';
import { type ActivityCommandOptions, createActivitySlashCommand } from './activity.js';
import { type AliasCommandOptions, createAliasSlashCommand } from './alias.js';
import { createArmySlashCommand } from './army.js';
import { type AttacksCommandOptions, createAttacksSlashCommand } from './attacks.js';
import { type AutoroleCommandOptions, createAutoroleSlashCommand } from './autorole.js';
import { type BlacklistCommandOptions, createBlacklistSlashCommand } from './blacklist.js';
import { type BoostsCommandOptions, createBoostsSlashCommand } from './boosts.js';
import { type CallerCommandOptions, createCallerSlashCommand } from './caller.js';
import { type CapitalCommandOptions, createCapitalSlashCommand } from './capital.js';
import { type CategoryCommandOptions, createCategorySlashCommand } from './category.js';
import { type ClanCommandOptions, createClanSlashCommand } from './clan.js';
import { type ClanGamesCommandOptions, createClanGamesSlashCommand } from './clan-games.js';
import { type ClansCommandOptions, createClansSlashCommand } from './clans.js';
import { type CompoCommandOptions, createCompoSlashCommand } from './compo.js';
import { type ConfigCommandOptions, createConfigSlashCommand } from './config.js';
import { type CwlCommandOptions, createCwlSlashCommand } from './cwl.js';
import { createDebugSlashCommand, type DebugCommandOptions } from './debug.js';
import { createDonationsSlashCommand, type DonationsCommandOptions } from './donations.js';
import { createEventsSlashCommand } from './events.js';
import { createGuildBanSlashCommand, type GuildBanCommandOptions } from './guild-ban.js';
import { createHelpSlashCommand } from './help.js';
import { createHistorySlashCommand, type HistoryCommandOptions } from './history.js';
import { createInviteSlashCommand } from './invite.js';
import { createLastSeenSlashCommand, type LastSeenCommandOptions } from './lastseen.js';
import { createLayoutSlashCommand, type LayoutCommandOptions } from './layout.js';
import { createLeaderboardSlashCommand, type LeaderboardCommandOptions } from './leaderboard.js';
import { createLegendSlashCommand, type LegendCommandOptions } from './legend.js';
import { createLineupSlashCommand, type LineupCommandOptions } from './lineup.js';
import { createLinkSlashCommand, type LinkCommandOptions } from './link.js';
import { createMembersSlashCommand, type MembersCommandOptions } from './members.js';
import { createNicknameSlashCommand, type NicknameCommandOptions } from './nickname.js';
import { createPlayerSlashCommand, type PlayerCommandOptions } from './player.js';
import { createProfileSlashCommand, type ProfileCommandOptions } from './profile.js';
import { createRemainingSlashCommand, type RemainingCommandOptions } from './remaining.js';
import { createRemindersSlashCommand, type RemindersCommandOptions } from './reminders.js';
import { createRushedSlashCommand, type RushedCommandOptions } from './rushed.js';
import { createSearchSlashCommand, type SearchCommandOptions } from './search.js';
import { createSetupClanSlashCommand, type SetupClanCommandOptions } from './setup-clan.js';
import { createStatsSlashCommand, type StatsCommandOptions } from './stats.js';
import { createStatusSlashCommand, type StatusCommandOptions } from './status.js';
import { createSummarySlashCommand, type SummaryCommandOptions } from './summary.js';
import { createTimezoneSlashCommand } from './timezone.js';
import { createUnitsSlashCommand, type UnitsCommandOptions } from './units.js';
import { createUpgradesSlashCommand, type UpgradesCommandOptions } from './upgrades.js';
import { createUsageSlashCommand, type UsageCommandOptions } from './usage.js';
import { createVerifySlashCommand, type VerifyCommandOptions } from './verify.js';
import { createWarSlashCommand, type WarCommandOptions } from './war.js';
import { createWarlogSlashCommand, type WarlogCommandOptions } from './warlog.js';
import { createWhitelistSlashCommand, type WhitelistCommandOptions } from './whitelist.js';

export interface BotCommandRegistryOptions {
  activity: ActivityCommandOptions;
  alias: AliasCommandOptions;
  attacks: AttacksCommandOptions;
  autorole: AutoroleCommandOptions;
  blacklist: BlacklistCommandOptions;
  boosts: BoostsCommandOptions;
  capital: CapitalCommandOptions;
  caller: CallerCommandOptions;
  category: CategoryCommandOptions;
  clanGames: ClanGamesCommandOptions;
  clan: ClanCommandOptions;
  clans: ClansCommandOptions;
  compo: CompoCommandOptions;
  config: ConfigCommandOptions;
  cwl: CwlCommandOptions;
  debug: DebugCommandOptions;
  donations: DonationsCommandOptions;
  guildBan: GuildBanCommandOptions;
  history: HistoryCommandOptions;
  lastSeen: LastSeenCommandOptions;
  layout: LayoutCommandOptions;
  leaderboard: LeaderboardCommandOptions;
  legend: LegendCommandOptions;
  lineup: LineupCommandOptions;
  link: LinkCommandOptions;
  members: MembersCommandOptions;
  nickname: NicknameCommandOptions;
  player: PlayerCommandOptions;
  profile: ProfileCommandOptions;
  remaining: RemainingCommandOptions;
  reminders: RemindersCommandOptions;
  rushed: RushedCommandOptions;
  search: SearchCommandOptions;
  setupClan: SetupClanCommandOptions;
  stats: StatsCommandOptions;
  summary: SummaryCommandOptions;
  status: StatusCommandOptions;
  units: UnitsCommandOptions;
  upgrades: UpgradesCommandOptions;
  usage: UsageCommandOptions;
  verify: VerifyCommandOptions;
  war: WarCommandOptions;
  warlog: WarlogCommandOptions;
  whitelist: WhitelistCommandOptions;
}

export function createBotCommandRegistry(options: BotCommandRegistryOptions): CommandRegistry {
  const registry = new CommandRegistry();

  registry.registerSlash(createActivitySlashCommand(options.activity));
  registry.registerSlash(createAliasSlashCommand(options.alias));
  registry.registerSlash(createArmySlashCommand());
  registry.registerSlash(createAttacksSlashCommand(options.attacks));
  registry.registerSlash(createAutoroleSlashCommand(options.autorole));
  registry.registerSlash(createBlacklistSlashCommand(options.blacklist));
  registry.registerSlash(createBoostsSlashCommand(options.boosts));
  registry.registerSlash(createCapitalSlashCommand(options.capital));
  registry.registerSlash(createCallerSlashCommand(options.caller));
  registry.registerSlash(createCategorySlashCommand(options.category));
  registry.registerSlash(createClanGamesSlashCommand(options.clanGames));
  registry.registerSlash(createClanSlashCommand(options.clan));
  registry.registerSlash(createClansSlashCommand(options.clans));
  registry.registerSlash(createCompoSlashCommand(options.compo));
  registry.registerSlash(createConfigSlashCommand(options.config));
  registry.registerSlash(createCwlSlashCommand(options.cwl));
  registry.registerSlash(createDebugSlashCommand(options.debug));
  registry.registerSlash(createDonationsSlashCommand(options.donations));
  registry.registerSlash(createEventsSlashCommand());
  registry.registerSlash(createGuildBanSlashCommand(options.guildBan));
  registry.registerSlash(createHelpSlashCommand());
  registry.registerSlash(createHistorySlashCommand(options.history));
  registry.registerSlash(createInviteSlashCommand());
  registry.registerSlash(createLastSeenSlashCommand(options.lastSeen));
  registry.registerSlash(createLayoutSlashCommand(options.layout));
  registry.registerSlash(createLeaderboardSlashCommand(options.leaderboard));
  registry.registerSlash(createLegendSlashCommand(options.legend));
  registry.registerSlash(createLineupSlashCommand(options.lineup));
  registry.registerSlash(createLinkSlashCommand(options.link));
  registry.registerSlash(createMembersSlashCommand(options.members));
  registry.registerSlash(createNicknameSlashCommand(options.nickname));
  registry.registerSlash(createPlayerSlashCommand(options.player));
  registry.registerSlash(createProfileSlashCommand(options.profile));
  registry.registerSlash(createRemainingSlashCommand(options.remaining));
  registry.registerSlash(createRemindersSlashCommand(options.reminders));
  registry.registerSlash(createRushedSlashCommand(options.rushed));
  registry.registerSlash(createSearchSlashCommand(options.search));
  registry.registerSlash(createSetupClanSlashCommand(options.setupClan));
  registry.registerSlash(createStatsSlashCommand(options.stats));
  registry.registerSlash(createSummarySlashCommand(options.summary));
  registry.registerSlash(createStatusSlashCommand(options.status));
  registry.registerSlash(createTimezoneSlashCommand());
  registry.registerSlash(createUnitsSlashCommand(options.units));
  registry.registerSlash(createUpgradesSlashCommand(options.upgrades));
  registry.registerSlash(createUsageSlashCommand(options.usage));
  registry.registerSlash(createVerifySlashCommand(options.verify));
  registry.registerSlash(createWarSlashCommand(options.war));
  registry.registerSlash(createWarlogSlashCommand(options.warlog));
  registry.registerSlash(createWhitelistSlashCommand(options.whitelist));

  return registry;
}
